name: "visual-loc"
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pytorch
  - pytorch-lightning
  - scipy
  - torchvision